language: python
env:
  global:
    - DATABASE_URL=postgresql://postgres@localhost/cloudstrype
    - DEPLOY_COUNT=0
    - DEPLOY_LIMIT=2
  matrix:
    - DJANGO=1.10
services:
  - postgresql
addons:
  postgresql: "9.5"
python:
  - "3.5"
  - "3.6"
install:
  - pip install --timeout=30 -r web/requirements.txt
before_script:
  - make deps
  - make lint
  - psql -c 'create database cloudstrype' -U postgres
script:
  - make ci-test
after_success:
  - make coveralls
before_deploy:
  - openssl aes-256-cbc -K $encrypted_dd65d59d6c9b_key -iv $encrypted_dd65d59d6c9b_iv -in deploy.tar.gz.enc -out deploy.tar.gz -d
  - tar xf deploy.tar.gz
deploy:
  skip_cleanup: true
  provider: script
  script:
    - make deploy
  on:
    branch: master
