version: '2'

networks:
  private:

services:

# Non-custom services (not our code).

  postgres:
    image: postgres:9.6-alpine
    networks:
      - private
    volumes:
      - /mnt/data/postgres:/var/lib/postgresql/data
    logging:
      driver: journald
      options:
        tag: "postgres"
    container_name: cloudstrype_db

  cache:
    image: memcached:1.4-alpine
    networks:
      - private
    logging:
      driver: journald
      options:
        tag: "memcached"
    container_name: cloudstrype_cache
    command: memcached -vv

  nginx:
    image: nginx:1.13.0-alpine
    volumes:
      - ./conf/nginx.conf.template:/etc/nginx/conf.d/cloudstrype.conf.template
      - ./ssl:/ssl
      - ./web:/web
      - ./scripts:/scripts
    depends_on:
      - web
    networks:
      - private
    ports:
      - "8000:80"
      - "8443:443"
    environment:
      - NGINX_HOST=cloudstrype.io
      - NGINX_PORT=80
    container_name: cloudstrype_nginx
    command: /scripts/nginx

  hitch:
    build:
      context: .
      dockerfile: ./hitch/Dockerfile
    image: cloudstrype/hitch
    volumes:
      - ./conf/hitch.conf.template:/etc/hitch/hitch.conf.template
      - ./ssl:/ssl
      - ./scripts:/scripts
    depends_on:
      - array
    networks:
      - private
    ports:
      - "8766:8766"
    environment:
      - ARRAY_HOST=array
      - ARRAY_PORT=8765
    container_name: cloudstrype_hitch
    command: /scripts/hitch

# Our code.

  web:
    build:
      context: .
      dockerfile: ./web/Dockerfile
    image: cloudstrype/web
    depends_on:
      - postgres
    networks:
      - private
    volumes:
      - /mnt/data/web:/data
      - ./web:/web
      - ./scripts:/scripts
    env_file:
      - .env
      - .env-private
      - .env-version
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - MIGRATE_HOST=migrate
      - MIGRATE_PORT=3024
    logging:
      driver: journald
      options:
        tag: "web"
    container_name: cloudstrype_web
    command: /scripts/web

  migrate:
    image: cloudstrype/web
    depends_on:
      - postgres
    networks:
      - private
    volumes:
      - /mnt/data/web:/data
      - ./web:/web
      - ./scripts:/scripts
    env_file:
      - .env
      - .env-private
      - .env-version
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - MIGRATE_PORT=3024
    logging:
      driver: journald
      options:
        tag: "migrate"
    container_name: cloudstrype_migrate
    command: /scripts/migrate

  cron:
    build:
      context: .
      dockerfile: ./cron/Dockerfile
    depends_on:
      - postgres
    networks:
      - private
    volumes:
    volumes:
      - /mnt/data/web:/data
      - ./web:/web
      - ./scripts:/scripts
      - ./cron/cron.d:/etc/cron.d
    env_file:
      - .env
      - .env-private
      - .env-version
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - MIGRATE_PORT=3024
    logging:
      driver: journald
      options:
        tag: "cron"
    container_name: cloudstrype_cron
    command: /scripts/cron

  array:
    image: cloudstrype/web
    networks:
      - private
    depends_on:
      - postgres
    volumes:
      - /mnt/data/web:/data
      - ./web:/web
      - ./scripts:/scripts
    env_file:
      - .env
      - .env-private
      - .env-version
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - MIGRATE_HOST=migrate
      - MIGRATE_PORT=3024
    logging:
      driver: journald
      options:
        tag: "array"
    container_name: cloudstrype_array
    command: /scripts/array
