version: '2'

services:

# Non-custom services (not our code).

  postgres:
    image: postgres:9.6-alpine
    container_name: postgres
    volumes:
      - /mnt/data/postgres:/var/lib/postgresql/data
    logging:
      driver: journald
      options:
        tag: "postgres"

  memcached:
    image: memcached:1.4-alpine
    container_name: memcached
    logging:
      driver: journald
      options:
        tag: "memcached"
    command: memcached -vv

  nginx:
    image: nginx:1.13.0-alpine
    container_name: nginx
    volumes:
      - "/etc/nginx/conf.d"
      - "/etc/nginx/vhost.d"
      - "/usr/share/nginx/html"
      - "./ssl:/etc/nginx/certs:ro"
    depends_on:
      - web
    ports:
      - "8000:80"
      - "8443:443"
    logging:
      driver: journald
      options:
        tag: "web"

# TODO: wrapper script to HUP hitch when cert is updated.
  hitch:
    build:
      context: .
      dockerfile: ./hitch/Dockerfile
    image: cloudstrype/hitch
    container_name: hitch
    volumes:
      - "./conf/hitch.template:/etc/hitch/hitch.conf"
      - "./ssl:/etc/hitch/certs:ro"
      - "./scripts:/scripts"
    depends_on:
      - array_server
    ports:
      - "8766:8766"
    environment:
      - ARRAY_HOST=array_server
      - ARRAY_PORT=8765
    logging:
      driver: journald
      options:
        tag: "hitch"
    command: /scripts/hitch

  nginx-gen:
    image: jwilder/docker-gen
    container_name: nginx-gen
    volumes:
      - "/var/run/docker.sock:/tmp/docker.sock:ro"
      - "./conf/nginx.template:/etc/docker-gen/templates/nginx.template:ro"
    volumes_from:
      - nginx
    logging:
      driver: journald
      options:
        tag: "nginx-gen"
    entrypoint: /usr/local/bin/docker-gen -notify-sighup nginx -watch -wait 5s:30s /etc/docker-gen/templates/nginx.template /etc/nginx/conf.d/default.conf

  letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: letsencrypt
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./ssl/:/etc/nginx/certs:rw"
    volumes_from:
      - "nginx"
    environment:
      - NGINX_DOCKER_GEN_CONTAINER=nginx-gen
    logging:
      driver: journald
      options:
        tag: "letsencrypt"

# Our code.

  web:
    build:
      context: .
      dockerfile: ./web/Dockerfile
    image: cloudstrype/web
    container_name: web
    depends_on:
      - postgres
    volumes:
      - /mnt/data/web:/data
      - ./web:/web
      - ./scripts:/scripts
    ports:
      - 8080
    env_file:
      - .env
      - .env-private
      - .env-version
    environment:
      - ARRAY_HOST=array_server
      - ARRAY_PORT=8001
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - MIGRATE_HOST=migrate
      - MIGRATE_PORT=3024
      - VIRTUAL_HOST=cloudstrype.localhost.io
      - VIRTUAL_PORT=8080
      - LETSENCRYPT_HOST=
      - LETSENCRYPT_EMAIL=
    logging:
      driver: journald
      options:
        tag: "web"
    command: /scripts/web

  migrate:
    image: cloudstrype/web
    container_name: migrate
    depends_on:
      - postgres
    volumes:
      - /mnt/data/web:/data
      - ./web:/web
      - ./scripts:/scripts
    env_file:
      - .env
      - .env-private
      - .env-version
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - MIGRATE_HOST=migrate
      - MIGRATE_PORT=3024
    logging:
      driver: journald
      options:
        tag: "migrate"
    command: /scripts/migrate

  cron:
    build:
      context: .
      dockerfile: ./cron/Dockerfile
    container_name: cron
    depends_on:
      - postgres
    volumes:
      - /mnt/data/web:/data
      - ./web:/web
      - ./scripts:/scripts
      - ./cron/cron.d:/etc/cron.d
    env_file:
      - .env
      - .env-private
      - .env-version
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - MIGRATE_HOST=migrate
      - MIGRATE_PORT=3024
    logging:
      driver: journald
      options:
        tag: "cron"
    command: /scripts/cron

  array_server:
    image: cloudstrype/web
    container_name: array_server
    depends_on:
      - postgres
    volumes:
      - /mnt/data/web:/data
      - ./web:/web
      - ./scripts:/scripts
    env_file:
      - .env
      - .env-private
      - .env-version
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - MIGRATE_HOST=migrate
      - MIGRATE_PORT=3024
    ports:
      - "8765:8765"
    logging:
      driver: journald
      options:
        tag: "array_server"
    command: /scripts/array
