# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-24 21:41
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.postgres.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import main.models


class Migration(migrations.Migration):

    replaces = [('main', '0001_initial'), ('main', '0002_auto_20170224_0354'), ('main', '0003_auto_20170224_0605'), ('main', '0004_auto_20170224_0638'), ('main', '0005_auto_20170224_0700'), ('main', '0006_auto_20170224_1820'), ('main', '0007_auto_20170224_1842'), ('main', '0008_auto_20170224_1934'), ('main', '0009_auto_20170224_2015')]

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('uid', models.CharField(max_length=255, unique=True)),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='email address')),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OAuth2AccessToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_token', models.TextField()),
                ('refresh_token', models.TextField(null=True)),
                ('expires', models.DateTimeField(null=True)),
            ],
            options={
                'verbose_name_plural': 'OAuth2 Access Tokens',
                'verbose_name': 'OAuth2 Access Token',
            },
        ),
        migrations.CreateModel(
            name='OAuth2LoginToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.OAuth2AccessToken')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'OAuth2 Login Tokens',
                'verbose_name': 'OAuth2 Login Token',
            },
        ),
        migrations.CreateModel(
            name='OAuth2Provider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.SmallIntegerField(choices=[(1, 'Dropbox'), (2, 'Onedrive'), (3, 'Box'), (4, 'Google Drive'), (5, 'Amazon'), (6, 'SmartFile')])),
                ('client_id', models.TextField()),
                ('client_secret', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'OAuth2 Providers',
                'verbose_name': 'OAuth2 Provider',
            },
        ),
        migrations.AddField(
            model_name='oauth2accesstoken',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tokens', to='main.OAuth2Provider'),
        ),
        migrations.AddField(
            model_name='oauth2accesstoken',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tokens', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Chunk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('md5', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='ChunkStorage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chunk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='storage', to='main.Chunk')),
            ],
        ),
        migrations.CreateModel(
            name='Directory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('display_name', models.CharField(max_length=45)),
                ('display_path', models.TextField()),
                ('parents', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=45), size=None)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            bases=(main.models.UidModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('size', models.IntegerField(default=0)),
                ('md5', models.CharField(max_length=32)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('directory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='main.Directory')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to=settings.AUTH_USER_MODEL)),
            ],
            bases=(main.models.UidModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='FileChunk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial', models.IntegerField()),
                ('chunk', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.Chunk')),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.File')),
            ],
        ),
        migrations.CreateModel(
            name='OAuth2StorageToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.IntegerField(default=0)),
                ('used', models.IntegerField(default=0)),
                ('token', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.OAuth2AccessToken')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='storage', to=settings.AUTH_USER_MODEL)),
                ('attrs', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'OAuth2 Storage Tokens',
                'verbose_name': 'OAuth2 Storage Token',
            },
            bases=(main.models.UidModelMixin, models.Model),
        ),
        migrations.AddField(
            model_name='chunkstorage',
            name='storage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.OAuth2StorageToken'),
        ),
        migrations.AddField(
            model_name='chunk',
            name='file',
            field=models.ManyToManyField(related_name='chunks', through='main.FileChunk', to='main.File'),
        ),
        migrations.AlterUniqueTogether(
            name='filechunk',
            unique_together=set([('file', 'serial')]),
        ),
        migrations.AddField(
            model_name='file',
            name='attrs',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='file',
            unique_together=set([('directory', 'name')]),
        ),
        migrations.AddField(
            model_name='directory',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dirs', to='main.Directory'),
        ),
        migrations.AddField(
            model_name='directory',
            name='attrs',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='directory',
            unique_together=set([('user', 'name', 'parents')]),
        ),
        migrations.AddField(
            model_name='chunkstorage',
            name='attrs',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='chunkstorage',
            unique_together=set([('chunk', 'storage')]),
        ),
        migrations.AddField(
            model_name='user',
            name='first_name',
            field=models.CharField(default='', max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='full_name',
            field=models.CharField(default='', max_length=64),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='filechunk',
            name='serial',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('replicas', models.SmallIntegerField(blank=True, null=True)),
                ('attrs', django.contrib.postgres.fields.jsonb.JSONField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='options', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
