# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-22 05:26
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.postgres.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('uid', models.CharField(max_length=255, unique=True)),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='email address')),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OAuth2AccessToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_token', models.TextField()),
                ('refresh_token', models.TextField(null=True)),
                ('expires', models.DateTimeField(null=True)),
            ],
            options={
                'verbose_name': 'OAuth2 Access Token',
                'verbose_name_plural': 'OAuth2 Access Tokens',
            },
        ),
        migrations.CreateModel(
            name='OAuth2Provider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True)),
                ('client_id', models.TextField()),
                ('client_secret', models.TextField()),
                ('authorization_url', models.URLField(max_length=255)),
                ('access_token_url', models.URLField(max_length=255)),
                ('user_profile_url', models.URLField(max_length=255)),
                ('scope', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=32), blank=True, null=True, size=None)),
                ('fields', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'OAuth2 Provider',
                'verbose_name_plural': 'OAuth2 Providers',
            },
        ),
        migrations.AddField(
            model_name='oauth2accesstoken',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tokens', to='main.OAuth2Provider'),
        ),
        migrations.AddField(
            model_name='oauth2accesstoken',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tokens', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='oauth2accesstoken',
            unique_together=set([('provider', 'user')]),
        ),
    ]
