# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-19 13:45
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.postgres.fields.jsonb
import django.contrib.postgres.search
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import main.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AllFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('attrs', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('search', django.contrib.postgres.search.SearchVectorField(blank=True, editable=False, null=True)),
                ('deleted', models.DateTimeField(null=True)),
            ],
            options={
                'db_table': 'main_file',
            },
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('attrs', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('search', django.contrib.postgres.search.SearchVectorField(blank=True, editable=False, null=True)),
                ('deleted', models.DateTimeField(null=True)),
            ],
            options={
                #'db_table': 'main_livefile',
                'managed': False,
            },
            bases=(main.models.UidModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Directory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('attrs', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('search', django.contrib.postgres.search.SearchVectorField(blank=True, editable=False, null=True)),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dirs', to='main.Directory')),
            ],
            bases=(main.models.UidModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='email address')),
                ('full_name', models.CharField(max_length=64)),
                ('first_name', models.CharField(editable=False, max_length=64)),
                ('last_name', models.CharField(editable=False, max_length=64)),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
            bases=(main.models.UidModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='FileVersion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.IntegerField(default=0)),
                ('md5', models.CharField(max_length=32)),
                ('sha1', models.CharField(max_length=40)),
                ('mime', models.CharField(max_length=64)),
                ('raid_level', models.SmallIntegerField(default=1)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('file', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='main.File')),
            ],
        ),
        migrations.AddField(
            model_name='allfile',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='all_files', to='main.Directory'),
        ),
        migrations.AddField(
            model_name='allfile',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='all_files', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='allfile',
            name='version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='all_current_of', to='main.FileVersion'),
        ),
        migrations.RunSQL([
            'CREATE VIEW "main_livefile" AS '
            'SELECT * FROM "main_file" '
            'WHERE "deleted" IS NULL'
        ,
            # Create and index on our File model for ONLY non-deleted files.
            'CREATE UNIQUE INDEX "unique_file_in_dir" '
            'ON "main_file" ("parent_id", "name") '
            'WHERE "deleted" IS NULL'
        ,
            'CREATE VIEW "main_deadfile" AS '
            'SELECT * FROM "main_file" '
            'WHERE "deleted" IS NOT NULL'
        ]),
        migrations.CreateModel(
            name='DeadFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('attrs', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('search', django.contrib.postgres.search.SearchVectorField(blank=True, editable=False, null=True)),
                ('deleted', models.DateTimeField(null=True)),
            ],
            options={
                'db_table': 'main_deadfile',
                'managed': False,
            },
            bases=(main.models.UidModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='DeadTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'main_filetag',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FileTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'main_filetag',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AllFileTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.AllFile')),
            ],
            options={
                'db_table': 'main_filetag',
            },
        ),
        migrations.CreateModel(
            name='BaseStorage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.SmallIntegerField(choices=[(1, 'Dropbox'), (2, 'Onedrive'), (3, 'Box'), (4, 'Google Drive'), (5, 'Array'), (6, 'Basic')])),
            ],
            options={
                'verbose_name': 'Storage',
                'verbose_name_plural': 'Storage',
            },
            bases=(main.models.UidModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='BaseUserStorage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.BigIntegerField(default=0)),
                ('used', models.BigIntegerField(default=0)),
                ('attrs', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
            ],
            bases=(main.models.UidModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Chunk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crc32', models.IntegerField(default=0)),
                ('md5', models.CharField(max_length=32)),
                ('size', models.IntegerField()),
            ],
            bases=(main.models.UidModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='ChunkStorage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attrs', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('chunk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='storage', to='main.Chunk')),
            ],
        ),
        migrations.CreateModel(
            name='DirectoryShare',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('directory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shared_with', to='main.Directory')),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shared_dirs', to='main.Directory')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shared_directories', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FileChunk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial', models.IntegerField(default=0)),
                ('chunk', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='filechunks', to='main.Chunk')),
            ],
        ),
        migrations.CreateModel(
            name='FileShare',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shared_with', to='main.File')),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shared_files', to='main.Directory')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shared_files', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FileStat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reads', models.IntegerField()),
                ('last', models.DateTimeField(auto_now=True)),
                ('file', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stats', to='main.File')),
            ],
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raid_level', models.SmallIntegerField(default=1)),
                ('raid_replicas', models.SmallIntegerField(default=1)),
                ('attrs', django.contrib.postgres.fields.jsonb.JSONField(null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='options', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ArrayStorage',
            fields=[
                ('basestorage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='main.BaseStorage')),
            ],
            bases=('main.basestorage',),
        ),
        migrations.CreateModel(
            name='ArrayUserStorage',
            fields=[
                ('baseuserstorage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='main.BaseUserStorage')),
                ('name', models.UUIDField(default=uuid.uuid4)),
            ],
            bases=('main.baseuserstorage',),
        ),
        migrations.CreateModel(
            name='BasicStorage',
            fields=[
                ('basestorage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='main.BaseStorage')),
            ],
            bases=('main.basestorage',),
        ),
        migrations.CreateModel(
            name='BasicUserStorage',
            fields=[
                ('baseuserstorage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='main.BaseUserStorage')),
                ('url', models.URLField(max_length=256)),
                ('username', models.CharField(max_length=256)),
                ('password', models.CharField(max_length=256)),
            ],
            bases=('main.baseuserstorage',),
        ),
        migrations.CreateModel(
            name='OAuth2Storage',
            fields=[
                ('basestorage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='main.BaseStorage')),
                ('client_id', models.TextField()),
                ('client_secret', models.TextField()),
            ],
            bases=('main.basestorage',),
        ),
        migrations.CreateModel(
            name='OAuth2UserStorage',
            fields=[
                ('baseuserstorage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='main.BaseUserStorage')),
                ('provider_uid', models.CharField(editable=False, max_length=255)),
                ('access_token', models.TextField()),
                ('refresh_token', models.TextField(null=True)),
                ('expires', models.DateTimeField(null=True)),
            ],
            options={
                'verbose_name': 'OAuth2 Access Token',
                'verbose_name_plural': 'OAuth2 Access Tokens',
            },
            bases=('main.baseuserstorage',),
        ),
        migrations.AddField(
            model_name='filechunk',
            name='fileversion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='filechunks', to='main.FileVersion'),
        ),
        migrations.AddField(
            model_name='directory',
            name='tags',
            field=models.ManyToManyField(to='main.Tag'),
        ),
        migrations.AddField(
            model_name='directory',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='chunkstorage',
            name='storage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='main.BaseUserStorage'),
        ),
        migrations.AddField(
            model_name='chunk',
            name='fileversion',
            field=models.ManyToManyField(related_name='chunks', through='main.FileChunk', to='main.FileVersion'),
        ),
        migrations.AddField(
            model_name='baseuserstorage',
            name='storage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.BaseStorage'),
        ),
        migrations.AddField(
            model_name='baseuserstorage',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='storages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='allfiletag',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Tag'),
        ),
        migrations.AlterUniqueTogether(
            name='fileshare',
            unique_together=set([('file', 'user')]),
        ),
        migrations.AlterUniqueTogether(
            name='filechunk',
            unique_together=set([('fileversion', 'serial')]),
        ),
        migrations.AlterUniqueTogether(
            name='directoryshare',
            unique_together=set([('directory', 'user')]),
        ),
        migrations.AlterUniqueTogether(
            name='directory',
            unique_together=set([('user', 'name', 'parent')]),
        ),
        migrations.AlterUniqueTogether(
            name='chunkstorage',
            unique_together=set([('chunk', 'storage')]),
        ),
    ]
