# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-19 07:35
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('socialaccount', '0003_extra_data_default_dict'),
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True)),
                ('type', models.SmallIntegerField(choices=[(1, 'Dropbox'), (2, 'Box'), (3, 'Onedrive'), (4, 'S3'), (5, 'Google Drive'), (6, 'ownCloud'), (7, 'WebDAV'), (8, 'FTP'), (9, 'Desktop Array')])),
            ],
        ),
        migrations.CreateModel(
            name='ProviderOAuth',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.Provider')),
                ('socialapp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='socialaccount.SocialApp')),
            ],
        ),
        migrations.CreateModel(
            name='Storage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True)),
                ('connection', django.contrib.postgres.fields.jsonb.JSONField()),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instances', to='main.Provider')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='storage', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
