# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-24 23:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial_squashed_0009_auto_20170224_2015'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='sha1',
            field=models.CharField(default='', max_length=40),
            preserve_default=False,
        ),
    ]
