# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-24 03:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='oauth2provider',
            name='access_token_url',
        ),
        migrations.RemoveField(
            model_name='oauth2provider',
            name='authorization_url',
        ),
        migrations.RemoveField(
            model_name='oauth2provider',
            name='user_profile_url',
        ),
    ]
