# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-19 16:28
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='allfile',
            name='tags',
            field=models.ManyToManyField(through='main.AllFileTag', to='main.Tag'),
        ),
        migrations.AlterField(
            model_name='allfile',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='main.Directory'),
        ),
        migrations.AlterField(
            model_name='allfile',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='allfile',
            name='version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='main.FileVersion'),
        ),
        migrations.AlterField(
            model_name='allfiletag',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='main.Tag'),
        ),
        migrations.AlterModelTable(
            name='file',
            table='main_livefile',
        ),
    ]
