# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-25 00:34
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_file_sha1'),
    ]

    operations = [
        migrations.AddField(
            model_name='directory',
            name='tags',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=36), null=True, size=None),
        ),
        migrations.AddField(
            model_name='file',
            name='tags',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=36), null=True, size=None),
        ),
    ]
