# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-24 06:05
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20170224_0354'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chunk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('md5', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='ChunkStorage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chunk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='storage', to='main.Chunk')),
            ],
        ),
        migrations.CreateModel(
            name='Directory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('display_name', models.CharField(max_length=45)),
                ('display_path', models.TextField()),
                ('parents', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=45), size=None)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            bases=(main.models.UidModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('size', models.IntegerField(default=0)),
                ('md5', models.CharField(max_length=32)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('directory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='main.Directory')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to=settings.AUTH_USER_MODEL)),
            ],
            bases=(main.models.UidModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='FileChunk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial', models.IntegerField()),
                ('chunk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Chunk')),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.File')),
            ],
        ),
        migrations.CreateModel(
            name='OAuth2StorageToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.IntegerField(default=0)),
                ('used', models.IntegerField(default=0)),
                ('token', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.OAuth2AccessToken')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'OAuth2 Storage Token',
                'verbose_name_plural': 'OAuth2 Storage Tokens',
            },
            bases=(main.models.UidModelMixin, models.Model),
        ),
        migrations.AddField(
            model_name='chunkstorage',
            name='storage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.OAuth2StorageToken'),
        ),
        migrations.AddField(
            model_name='chunk',
            name='file',
            field=models.ManyToManyField(related_name='chunks', through='main.FileChunk', to='main.File'),
        ),
        migrations.AlterUniqueTogether(
            name='filechunk',
            unique_together=set([('file', 'serial')]),
        ),
        migrations.AlterUniqueTogether(
            name='file',
            unique_together=set([('directory', 'name')]),
        ),
        migrations.AlterUniqueTogether(
            name='directory',
            unique_together=set([('user', 'name', 'parents')]),
        ),
        migrations.AlterUniqueTogether(
            name='chunkstorage',
            unique_together=set([('chunk', 'storage')]),
        ),
    ]
