# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-23 16:16
from __future__ import unicode_literals

from django.contrib.auth.hashers import make_password
from django.db import migrations


# Duplicated here, as Models don't have custom attributes!
PROVIDER_DROPBOX = 1
PROVIDER_ONEDRIVE = 2
PROVIDER_BOX = 3
PROVIDER_GOOGLE = 4
PROVIDER_ARRAY = 5
PROVIDER_BASIC = 6


def forwards(apps, schema_editor):
    """
    Create user and cloud providers.
    """
    User = apps.get_model('main', 'User')
    OAuth2Storage = apps.get_model('main', 'OAuth2Storage')

    u = User.objects.create(email='admin@cloudstrype.localhost', is_admin=True,
                            is_active=True)
    u.password = make_password('password')
    u.save()

    # Add some cloud storage providers. The OAuth2 CLIENT_SECRET will come from
    # the environment (not in source control.)
    OAuth2Storage.objects.create(
        provider=PROVIDER_DROPBOX,
        client_id='almcjss94o9mukm')

    OAuth2Storage.objects.create(
        provider=PROVIDER_ONEDRIVE,
        client_id='4c785ebb-08cf-43dd-91b6-e7d2c29c82bc')

    OAuth2Storage.objects.create(
        provider=PROVIDER_BOX,
        client_id='1qo83msmk38g741c1ak7f5icq09b8has')

    OAuth2Storage.objects.create(
        provider=PROVIDER_GOOGLE,
        client_id='598229801997-vl1rjc7umkf39cdapp6r8jr36t689tq5.apps.'
                  'googleusercontent.com')


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20170521_0033'),
    ]

    operations = [
        migrations.RunPython(forwards)
    ]
