# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-18 19:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20170402_1607'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileVersion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='chunk',
            name='md5',
            field=models.CharField(default='', max_length=32),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='file',
            name='version',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterUniqueTogether(
            name='file',
            unique_together=set([('parent', 'name', 'version')]),
        ),
        migrations.AddField(
            model_name='fileversion',
            name='file',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.File'),
        ),
        migrations.AddIndex(
            model_name='fileversion',
            index=models.Index(fields=['file', 'version'], name='main_fileve_file_id_95840b_idx'),
        ),
    ]
