# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-04 01:20
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20170402_1607'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseuserstorage',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='storages', to=settings.AUTH_USER_MODEL),
        ),
    ]
