# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-24 06:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20170224_0605'),
    ]

    operations = [
        migrations.AddField(
            model_name='directory',
            name='parent',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='dirs', to='main.Directory'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='first_name',
            field=models.CharField(default='', max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='full_name',
            field=models.CharField(default='', max_length=64),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='filechunk',
            name='chunk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.Chunk'),
        ),
        migrations.AlterField(
            model_name='filechunk',
            name='serial',
            field=models.IntegerField(default=0),
        ),
    ]
