# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-05 16:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20170404_0120'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chunk',
            name='md5',
        ),
        migrations.AddField(
            model_name='chunk',
            name='crc32',
            field=models.IntegerField(default=0),
        ),
    ]
