# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-18 19:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20170518_1946'),
    ]

    operations = [
        migrations.RunSQL([
            "CREATE FUNCTION main_file_version() RETURNS trigger AS $$"
            "begin"
            "  INSERT INTO main_fileversion (file_id, version) "
            "  VALUES (new.id, new.version) "
            "  ON CONFLICT(file_id) DO UPDATE SET version = new.version;"
            "  RETURN new;"
            "end"
            "$$ LANGUAGE plpgsql"
        ,
            "CREATE TRIGGER main_file_version_trigger BEFORE INSERT OR UPDATE"
            "    ON main_file FOR EACH ROW EXECUTE PROCEDURE main_file_version()"
        ,
        ], [
            "DROP FUNCTION main_file_version()",
            "DROP TRIGGER main_file_version_trigger ON main_file",
        ]),
    ]
