# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-07 01:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20170307_0108'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='mime',
            field=models.CharField(default='application/unknown', max_length=64),
        ),
    ]
