# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-10 04:37
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_file_mime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chunkstorage',
            name='storage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='main.OAuth2StorageToken'),
        ),
        migrations.AlterField(
            model_name='oauth2storagetoken',
            name='token',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='storage', to='main.OAuth2AccessToken'),
        ),
        migrations.AlterField(
            model_name='option',
            name='attrs',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
    ]
