# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-11 05:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20170310_0437'),
    ]

    operations = [
        migrations.AddField(
            model_name='directory',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
