#!/bin/sh -x

/wait-for -t 60 ${MIGRATE_HOST}:${MIGRATE_PORT} -- echo "Migrations complete!"

cd /web/cloudstrype
# /usr/bin/env python3 manage.py collectstatic --noinput

/usr/bin/env python3 manage.py runserver 0.0.0.0:8080
